version: 2.1

jobs:
  test:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/brazilian-utils/go-brazilian-utils
    steps:
      - checkout
      - run: go test -v ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
